[package]
name = "rust-learn"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4"
serde = { version = "1.0", features = ["derive"] }
log = "0.4"
serde_json = "1.0"
derive_more = "0.99"
dotenv = "0.15.0"
validator = { version = "0.16", features = ["derive"] }
actix-web-validator = "5.0.1"
tokio = "1.32.0"
