[package]
name = "rust-learn"
version = "0.1.0"
authors = ["Sofwan Lawal <no@mail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4"
actix-cors = "0.6"
serde = { version = "1.0", features = ["derive"] }
log = "0.4"
serde_json = "1"
derive_more = "0.99"
dotenv = "0.15.0"
validator = { version = "0.16", features = ["derive"] }
actix-web-validator = "5"
tokio = "1"
env_logger = "0.10.0"
jsonwebtoken = "8"
ulid = "1"
argon2 = "0.5.1"
chrono = { version = "0.4", features = ["serde"] }
futures-util = "0.3.28"

