version: '3.8'

services:
  postgres_project_db:
    image: postgres:15
#    restart: always
    environment:
      POSTGRES_USER: u-wg04z
      POSTGRES_PASSWORD: wg04zC
    volumes:
      - postgres_project_db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - .env

  mysql_project_db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
#    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: database
      MYSQL_USER: u-wg04z
      MYSQL_PASSWORD: wg04zC
    volumes:
      - mysql_project_db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    env_file:
      - .env

  redis_project_db:
    image: redis:2
    command: /bin/sh -c "redis-server --requirepass wg04zC"
    volumes:
        - redis_project_db_data:/data
    ports:
      - "6379:6379"
    env_file:
      - .env

  mongo_project_db:
    image: mongo:7
    environment:
      MONGO_INITDB_ROOT_USERNAME: u-wg04z
      MONGO_INITDB_ROOT_PASSWORD: wg04zC
    volumes:
      - mongo_project_db_data:/data/db
    ports:
      - "27017:27017"
    env_file:
      - .env

  rabbitmq_project_db:
    image: rabbitmq:3
    environment:
      RABBITMQ_DEFAULT_USER: u-wg04z
      RABBITMQ_DEFAULT_PASS: wg04zC
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_project_db_data:/var/lib/rabbitmq
    env_file:
      - .env


volumes:
  postgres_project_db_data:
  mysql_project_db_data:
  redis_project_db_data:
  mongo_project_db_data:
  rabbitmq_project_db_data:
