edition = "2021"
reorder_imports = true
imports_layout = "HorizontalVertical"
imports_granularity= "Crate"
condense_wildcard_suffixes = true
format_strings = true
normalize_comments= true
normalize_doc_attributes = true
reorder_impl_items=true
use_try_shorthand = true
wrap_comments = true
